const USER_GET_TYPES = {
  GET_REQUEST_SENDING: "GET_REQUEST_SENDING",
  GET_REQUEST_SUCCESS: "GET_REQUEST_SUCCESS",
  GET_REQUEST_FAILURE: "GET_REQUEST_FAILURE",
};

const USER_ADD_TYPES = {
  ADD_REQUEST_SENDING: "ADD_REQUEST_SENDING",
  ADD_REQUEST_SUCCESS: "ADD_REQUEST_SUCCESS",
  ADD_REQUEST_FAILURE: "ADD_REQUEST_FAILURE",
};

export { USER_GET_TYPES, USER_ADD_TYPES };
